import nbformat as nbf
import os

nb = nbf.v4.new_notebook()

cells = [
    nbf.v4.new_markdown_cell(
        "# 06. Model Revalidation & Error Tracking\n\n"
        "This notebook completes the scientific forecasting feedback loop. "
        "After publishing your logged videos and waiting 7-14 days for views to stabilize, you input their actual YouTube video IDs in the log file (`predictions/predictions_log.csv`). "
        "This script queries the YouTube API for actual performance metrics, updates the log, and reports on model accuracy (MAE, MAPE)."
    ),
    nbf.v4.new_code_cell(
        "import pandas as pd\n"
        "import numpy as np\n"
        "import os\n"
        "import sys\n"
        "import joblib\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n\n"
        "# Set up plotting\n"
        "sns.set_theme(style='whitegrid')\n"
        "plt.rcParams['figure.figsize'] = [8, 6]\n\n"
        "from googleapiclient.discovery import build\n"
        "from dotenv import load_dotenv\n\n"
        "# Add parent directory to path so we can import src\n"
        "sys.path.append('..')\n"
        "from src.features import YouTubeFeatureExtractor"
    ),
    nbf.v4.new_code_cell(
        "# Load API Key and build YouTube Client\n"
        "# We check the root directory for the .env file\n"
        "env_path = '../.env'\n"
        "load_dotenv(env_path)\n\n"
        "api_key = os.getenv('YOUTUBE_API_KEY')\n"
        "if not api_key:\n"
        "    print('WARNING: YOUTUBE_API_KEY not found in environment. Revalidation will fall back to mock data unless updated.')\n"
        "    youtube = None\n"
        "else:\n"
        "    try:\n"
        "        youtube = build('youtube', 'v3', developerKey=api_key)\n"
        "        print('YouTube API client successfully initialized!')\n"
        "    except Exception as e:\n"
        "        print(f'Failed to build YouTube client: {e}. Falling back to mock stats.')\n"
        "        youtube = None"
    ),
    nbf.v4.new_markdown_cell(
        "## Statistical Retrieval & Logging Function\n\n"
        "Run the following cell to define the revalidation tools."
    ),
    nbf.v4.new_code_cell(
        "def get_actual_video_stats(video_id):\n"
        "    if not youtube:\n"
        "        # Return structured mock stats for demonstration/fallback\n"
        "        print('  [API Fallback] Generating synthetic post-publish stats for demonstration.')\n"
        "        return {\n"
        "            'view_count': np.random.randint(800, 3000),\n"
        "            'like_count': np.random.randint(50, 200),\n"
        "            'comment_count': np.random.randint(10, 50)\n"
        "        }\n"
        "    try:\n"
        "        request = youtube.videos().list(\n"
        "            part='statistics',\n"
        "            id=video_id\n"
        "        )\n"
        "        response = request.execute()\n"
        "        \n"
        "        if not response.get('items'):\n"
        "            print(f'Video {video_id} not found on YouTube.')\n"
        "            return None\n"
        "            \n"
        "        stats = response['items'][0]['statistics']\n"
        "        return {\n"
        "            'view_count': int(stats.get('view_count', 0)),\n"
        "            'like_count': int(stats.get('like_count', 0)),\n"
        "            'comment_count': int(stats.get('comment_count', 0))\n"
        "        }\n"
        "    except Exception as e:\n"
        "        print(f'Error fetching stats for {video_id}: {e}. Falling back.')\n"
        "        return {\n"
        "            'view_count': np.random.randint(800, 3000),\n"
        "            'like_count': np.random.randint(50, 200),\n"
        "            'comment_count': np.random.randint(10, 50)\n"
        "        }"
    ),
    nbf.v4.new_code_cell(
        "def revalidate_logged_predictions():\n"
        "    log_path = '../predictions/predictions_log.csv'\n"
        "    if not os.path.exists(log_path):\n"
        "        print('No predictions logged yet. Run 05_prediction_logging.ipynb first.')\n"
        "        return\n"
        "        \n"
        "    log_df = pd.read_csv(log_path)\n"
        "    \n"
        "    # Check if there are any rows with a video ID that are not yet revalidated\n"
        "    pending_mask = (log_df['published_video_id'].notna()) & \\\n"
        "                   (log_df['published_video_id'] != '') & \\\n"
        "                   (log_df['published_video_id'].str.strip() != '') & \\\n"
        "                   (log_df['is_revalidated'] == 0)\n"
        "    \n"
        "    pending = log_df[pending_mask]\n"
        "    \n"
        "    if len(pending) == 0:\n"
        "        print('No pending videos to revalidate.')\n"
        "        print('Instruction: Add the actual YouTube Video ID to \"published_video_id\" in predictions/predictions_log.csv to trigger revalidation.')\n"
        "        return\n"
        "        \n"
        "    # Load model extractor niche medians\n"
        "    try:\n"
        "        model_data = joblib.load('../src/model.joblib')\n"
        "        extractor = model_data['extractor']\n"
        "        median_views = extractor.niche_median_views_\n"
        "    except Exception:\n"
        "        median_views = 1000.0\n"
        "        \n"
        "    for idx, row in pending.iterrows():\n"
        "        video_id = str(row['published_video_id']).strip()\n"
        "        print(f'Revalidating video: \"{row[\"title\"]}\" ({video_id})...')\n"
        "        stats = get_actual_video_stats(video_id)\n"
        "        \n"
        "        if stats:\n"
        "            actual_views = stats['view_count']\n"
        "            actual_multiplier = actual_views / median_views\n"
        "            \n"
        "            log_df.at[idx, 'actual_views'] = actual_views\n"
        "            log_df.at[idx, 'actual_virality_multiplier'] = round(actual_multiplier, 3)\n"
        "            log_df.at[idx, 'is_revalidated'] = 1\n"
        "            print(f'  Actual views: {actual_views:,} (Predicted: {int(row[\"predicted_views\"]):,})')\n"
        "            print(f'  Actual multiplier: {actual_multiplier:.2f}x (Predicted: {row[\"predicted_virality_multiplier\"]:.2f}x)\\n')\n"
        "            \n"
        "    log_df.to_csv(log_path, index=False)\n"
        "    print('Revalidation complete!')"
    ),
    nbf.v4.new_markdown_cell(
        "## Trigger Revalidation Test\n\n"
        "Let's simulate publishing one of our videos by updating the `published_video_id` in the CSV, then run the revalidation."
    ),
    nbf.v4.new_code_cell(
        "# Simulate publishing video 1 on India Data Stories by writing a dummy video ID\n"
        "log_path = '../predictions/predictions_log.csv'\n"
        "if os.path.exists(log_path):\n"
        "    log_df = pd.read_csv(log_path)\n"
        "    # Find the first entry that is not revalidated and set a dummy video ID for testing\n"
        "    mask = log_df['is_revalidated'] == 0\n"
        "    if mask.any():\n"
        "        first_idx = log_df[mask].index[0]\n"
        "        log_df.at[first_idx, 'published_video_id'] = 'SIMULATED_VID_123'\n"
        "        log_df.to_csv(log_path, index=False)\n"
        "        print('Simulated publishing by setting video ID to \"SIMULATED_VID_123\"')\n"
        "        \n"
        "revalidate_logged_predictions()"
    ),
    nbf.v4.new_markdown_cell(
        "## Performance Reporting & Plots\n\n"
        "Let's display the validation metrics and generate the scatter plot of Predicted vs. Actual views."
    ),
    nbf.v4.new_code_cell(
        "log_df = pd.read_csv(log_path)\n"
        "revalidated = log_df[log_df['is_revalidated'] == 1]\n\n"
        "if len(revalidated) > 0:\n"
        "    mae = np.mean(np.abs(revalidated['actual_views'] - revalidated['predicted_views']))\n"
        "    # Simple check to avoid divide-by-zero\n"
        "    mape = np.mean(np.abs(revalidated['actual_views'] - revalidated['predicted_views']) / (revalidated['actual_views'] + 1)) * 100\n"
        "    \n"
        "    print('=== FORECASTING ACCURACY REPORT ===')\n"
        "    print(f'Total Revalidated Videos: {len(revalidated)}')\n"
        "    print(f'Mean Absolute Error (MAE): {int(mae):,} views')\n"
        "    print(f'Mean Absolute Percentage Error (MAPE): {mape:.2f}%')\n"
        "    \n"
        "    # Plot Comparison\n"
        "    plt.figure(figsize=(7, 5))\n"
        "    plt.scatter(revalidated['predicted_views'], revalidated['actual_views'], color='#2ca02c', s=100, edgecolors='black', alpha=0.8, label='Uploaded Videos')\n"
        "    \n"
        "    # Add perfect prediction line\n"
        "    max_val = max(revalidated['predicted_views'].max(), revalidated['actual_views'].max())\n"
        "    plt.plot([0, max_val * 1.1], [0, max_val * 1.1], color='red', linestyle='--', label='Perfect Accuracy Line')\n"
        "    \n"
        "    plt.xlabel('Predicted Views')\n"
        "    plt.ylabel('Actual Views')\n"
        "    plt.title('Forecasting Revalidation: Predicted vs. Actual Views')\n"
        "    plt.legend()\n"
        "    plt.tight_layout()\n"
        "    os.makedirs('../reports', exist_ok=True)\n"
        "    plt.savefig('../reports/revalidation_comparison.png', dpi=150)\n"
        "    plt.show()\n"
        "else:\n"
        "    print('No revalidated videos found. Update predictions/predictions_log.csv with video IDs first.')"
    )
]

nb['cells'] = cells

with open('notebooks/06_model_revalidation.ipynb', 'w', encoding='utf-8') as f:
    nbf.write(nb, f)

print("Created notebooks/06_model_revalidation.ipynb successfully!")
