import nbformat as nbf
import os

nb = nbf.v4.new_notebook()

cells = [
    nbf.v4.new_markdown_cell(
        "# 04. Model Building & Creator Recommendation Engine\n\n"
        "This notebook loads the engineered feature datasets from Step 2, trains multiple Machine Learning models (Ridge, Random Forest, HistGradientBoosting) to predict video virality, evaluates them using `GroupKFold` cross-validation grouped by channel ID, extracts the strongest virality drivers, and implements an interactive creator recommendation tool."
    ),
    nbf.v4.new_code_cell(
        "import pandas as pd\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n"
        "import os\n"
        "import sys\n"
        "import joblib\n\n"
        "from sklearn.model_selection import GroupKFold\n"
        "from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor\n"
        "from sklearn.linear_model import Ridge\n"
        "from sklearn.metrics import mean_absolute_error, r2_score\n\n"
        "# Set up plotting styles\n"
        "sns.set_theme(style='whitegrid')\n"
        "plt.rcParams['figure.figsize'] = [10, 6]\n"
        "plt.rcParams['font.size'] = 11\n\n"
        "# Add parent directory to path so we can import src\n"
        "sys.path.append('..')\n"
        "from src.features import YouTubeFeatureExtractor"
    ),
    nbf.v4.new_code_cell(
        "# Load feature datasets and merge them for a robust combined training set\n"
        "try:\n"
        "    pop_df = pd.read_csv('../data/processed/features_popular.csv')\n"
        "    pop_df['is_underserved'] = 0\n"
        "    und_df = pd.read_csv('../data/processed/features_underserved.csv')\n"
        "    und_df['is_underserved'] = 1\n"
        "    \n"
        "    # Combine both datasets\n"
        "    df = pd.concat([pop_df, und_df], ignore_index=True)\n"
        "    print(f'Total dataset size: {len(df)} videos across {df[\"channel_id\"].nunique()} unique channels')\n"
        "except FileNotFoundError as e:\n"
        "    print(f'Error loading feature files: {e}. Did you run 03_eda_and_features.ipynb first?')\n"
    ),
    nbf.v4.new_code_cell(
        "# Define features list and target variable\n"
        "features_list = [\n"
        "    'duration_minutes',\n"
        "    'tags_count',\n"
        "    'title_char_count',\n"
        "    'title_word_count',\n"
        "    'title_has_number',\n"
        "    'title_has_question',\n"
        "    'title_has_exclamation',\n"
        "    'title_has_all_caps',\n"
        "    'title_emotional_trigger_count',\n"
        "    'is_weekend',\n"
        "    'publish_hour_ist',\n"
        "    'publish_day_of_week',\n"
        "    'is_underserved',\n"
        "    'log_channel_subscribers'\n"
        "]\n\n"
        "target = 'virality_ratio_median' # Target representing log10(views/median_views + 0.01)\n"
        "print('Features list count:', len(features_list))\n"
        "print('Target variable:', target)"
    ),
    nbf.v4.new_markdown_cell(
        "## Cross-Validation using GroupKFold\n\n"
        "We group by `channel_id` so that videos from the same channel are never in both the training set and the test set at the same time. This is a truer measure of generalizability to a brand new channel."
    ),
    nbf.v4.new_code_cell(
        "X = df[features_list]\n"
        "y = df[target]\n"
        "groups = df['channel_id']\n\n"
        "# Define 5-fold GroupKFold based on channel_id\n"
        "n_splits = min(5, df['channel_id'].nunique())\n"
        "gkf = GroupKFold(n_splits=n_splits)\n\n"
        "models = {\n"
        "    'Ridge Regression': Ridge(alpha=10.0),\n"
        "    'Random Forest': RandomForestRegressor(n_estimators=100, random_state=42, max_depth=6),\n"
        "    'HistGradientBoosting': HistGradientBoostingRegressor(random_state=42, max_depth=4)\n"
        "}\n\n"
        "results_mae = {name: [] for name in models.keys()}\n"
        "results_r2 = {name: [] for name in models.keys()}\n\n"
        "for train_idx, test_idx in gkf.split(X, y, groups):\n"
        "    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]\n"
        "    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]\n"
        "    \n"
        "    for name, model in models.items():\n"
        "        model.fit(X_train, y_train)\n"
        "        preds = model.predict(X_test)\n"
        "        mae = mean_absolute_error(y_test, preds)\n"
        "        r2 = r2_score(y_test, preds)\n"
        "        results_mae[name].append(mae)\n"
        "        results_r2[name].append(r2)\n\n"
        "print('=== GroupKFold Cross Validation Scores (Normalised Virality Target) ===\\n')\n"
        "for name in models.keys():\n"
        "    mean_mae = np.mean(results_mae[name])\n"
        "    mean_r2 = np.mean(results_r2[name])\n"
        "    print(f'{name:20} | Mean MAE: {mean_mae:.4f} | Mean R2: {mean_r2:.4f}')"
    ),
    nbf.v4.new_markdown_cell(
        "## Feature Importances\n\n"
        "Let's train our final Random Forest model on the complete combined dataset and analyze feature importances to see which factors contribute most heavily to virality."
    ),
    nbf.v4.new_code_cell(
        "final_model = RandomForestRegressor(n_estimators=150, random_state=42, max_depth=8)\n"
        "final_model.fit(X, y)\n\n"
        "# Get feature importances\n"
        "importances = final_model.feature_importances_\n"
        "feat_imp = pd.Series(importances, index=features_list).sort_values(ascending=False)\n\n"
        "# Plot\n"
        "plt.figure(figsize=(10, 6))\n"
        "sns.barplot(x=feat_imp.values, y=feat_imp.index, hue=feat_imp.index, palette='viridis', legend=False)\n"
        "plt.title('Feature Importances for YouTube Virality')\n"
        "plt.xlabel('Relative Importance Score')\n"
        "plt.ylabel('Features')\n"
        "plt.tight_layout()\n"
        "plt.savefig('../reports/feature_importances.png', dpi=150)\n"
        "plt.show()\n\n"
        "print('Ranked list of driver features:')\n"
        "print(feat_imp)"
    ),
    nbf.v4.new_markdown_cell(
        "## Creator Video Recommendation Engine\n\n"
        "Let's write a function that takes a proposed video idea, calculates its features, predicts its estimated virality multiplier, and outputs structured optimizations."
    ),
    nbf.v4.new_code_cell(
        "# Load raw datasets and fit feature extractor globally\n"
        "popular_raw = pd.read_csv('../data/raw/popular_niche/videos.csv')\n"
        "underserved_raw = pd.read_csv('../data/raw/underserved_niche/videos.csv')\n\n"
        "global_extractor = YouTubeFeatureExtractor()\n"
        "global_extractor.fit(pd.concat([popular_raw, underserved_raw], ignore_index=True))\n\n"
        "def recommend_video_optimizations(title, duration_minutes, publish_hour_ist, publish_day_of_week=2, is_underserved=1, subscribers=100):\n"
        "    # Create mock dataframe row\n"
        "    mock_row = pd.DataFrame([{\n"
        "        'title': title,\n"
        "        'description': '',\n"
        "        'tags': '[]',\n"
        "        'duration_seconds': duration_minutes * 60,\n"
        "        'published_at': pd.Timestamp.now(tz='UTC').isoformat(),\n"
        "        'view_count': 0,\n"
        "        'channel_subscriber_count': subscribers,\n"
        "        'channel_id': 'mock_channel_id'\n"
        "    }])\n"
        "    \n"
        "    # Extract features using globally fitted extractor\n"
        "    features = global_extractor.transform(mock_row)\n"
        "    \n"
        "    # Override temporal features explicitly to match input arguments\n"
        "    features['publish_hour_ist'] = publish_hour_ist\n"
        "    features['publish_day_of_week'] = publish_day_of_week\n"
        "    features['is_weekend'] = int(publish_day_of_week >= 5)\n"
        "    features['is_underserved'] = is_underserved\n"
        "    \n"
        "    X_pred = features[features_list]\n"
        "    pred_virality = final_model.predict(X_pred)[0]\n"
        "    \n"
        "    # Convert log10 target back to multiplier\n"
        "    # virality_ratio_median = log10(views / median + 0.01)\n"
        "    # Multiplier = 10^virality - 0.01\n"
        "    multiplier = 10**pred_virality - 0.01\n"
        "    estimated_views = max(0, multiplier * global_extractor.niche_median_views_)\n"
        "    \n"
        "    print('========================================')\n"
        "    print('    CREATOR VIDEO OPTIMIZATION TOOL     ')\n"
        "    print('========================================')\n"
        "    print(f'Proposed Title: \"{title}\"')\n"
        "    print(f'Niche:          {\"India Economy & Data Stories\" if is_underserved else \"Personal Finance\"}')\n"
        "    print(f'Estimated Virality Multiplier: {multiplier:.2f}x channel median views')\n"
        "    print(f'Estimated Views (for a new channel): {int(estimated_views):,}')\n"
        "    print('----------------------------------------')\n"
        "    print('Diagnostics & Recommendations:')\n"
        "    \n"
        "    recs = []\n"
        "    if len(title) > 70:\n"
        "        recs.append('- Title is too long (over 70 chars). Shorten it to ~45-60 characters for better mobile CTR.')\n"
        "    elif len(title) < 30:\n"
        "        recs.append('- Title is very short. Add descriptive keywords or a hook to stand out.')\n"
        "        \n"
        "    if not any(c.isdigit() for c in title):\n"
        "        recs.append('- Include a numerical metric or stat in the title (e.g. \"₹10,000\", \"5 Steps\") to boost curiosity.')\n"
        "        \n"
        "    if '?' not in title:\n"
        "        recs.append('- Consider rephrasing title as a question (e.g. \"Why does...?\" or \"Is this...?\") to spark a click.')\n"
        "        \n"
        "    if duration_minutes < 8:\n"
        "        recs.append('- Video is short (< 8 mins). Standard high-performance economy videos tend to be 10-15 minutes.')\n"
        "    elif duration_minutes > 18:\n"
        "        recs.append('- Video is very long (> 18 mins). Keep it closer to 12 minutes to maintain high audience retention.')\n"
        "        \n"
        "    if not (17 <= publish_hour_ist <= 21):\n"
        "        recs.append('- Upload hour is outside peak (5 PM - 9 PM IST). Evening uploads maximize initial velocity.')\n"
        "        \n"
        "    if len(recs) == 0:\n"
        "        print('✅ Excellent! Your proposed video structure matches all top-performing guidelines.')\n"
        "    else:\n"
        "        for r in recs:\n"
        "            print(r)\n"
        "    return multiplier\n\n"
        "# Let's run a test on two ideas!\n"
        "print('TESTING 2 IDEAS SIDE-BY-SIDE:\\n')\n"
        "ratio1 = recommend_video_optimizations(\n"
        "    title='How to invest money in India',\n"
        "    duration_minutes=6.0,\n"
        "    publish_hour_ist=12,\n"
        "    is_underserved=1\n"
        ")\n"
        "print('\\n')\n"
        "ratio2 = recommend_video_optimizations(\n"
        "    title='Why India is running out of water: 5 Shocking Facts',\n"
        "    duration_minutes=12.5,\n"
        "    publish_hour_ist=19,\n"
        "    is_underserved=1\n"
        ")"
    ),
    nbf.v4.new_markdown_cell(
        "## Save Model Artifacts\n\n"
        "We save the final Random Forest model, the features list, and the fitted extractor to a `.joblib` file so we can load it in our prediction logging and validation scripts."
    ),
    nbf.v4.new_code_cell(
        "# Save the model components\n"
        "model_data = {\n"
        "    'model': final_model,\n"
        "    'features_list': features_list,\n"
        "    'extractor': global_extractor\n"
        "}\n\n"
        "os.makedirs('../src', exist_ok=True)\n"
        "joblib.dump(model_data, '../src/model.joblib')\n"
        "print('Trained model saved successfully to src/model.joblib!')"
    )
]

nb['cells'] = cells

with open('notebooks/04_model_building.ipynb', 'w', encoding='utf-8') as f:
    nbf.write(nb, f)

print("Created notebooks/04_model_building.ipynb successfully!")
